"""description

Revision ID: 17a6af239aa3
Revises: 22f1025d4b6e
Create Date: 2025-11-16 07:25:54.876467

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '17a6af239aa3'
down_revision = '22f1025d4b6e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('moderation_flags', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'moderation_flags')
    # ### end Alembic commands ###
